### ISSUE TITLE
News API

### ISSUE THREAD

**Issue by swagat-das** [swagat-das/Cognizen-Website#7]
**Implement the News API** in the about.html page after making it look-alike to the index.html, which API will dynamically fetch news updates on the website.

**Comment by voidrohit** [comment]
1. Can I use any other News API ? OR Can I scrape news from another website and show it on this website?
2. What type of News do we need?

**Comment by swagat-das** [comment]
1. Better to use API then web scrapping.
2. News that are political and economical of nature are requested. It will be good if it is a mixture of National and International.

**Comment by voidrohit** [comment]
Can you add "hacktoberfest" topic to this repository or add the "hacktoberfest-accepted" label to the PR? So that it will eligible for the Hacktoberfest 2020.
Reference: [Updated Rule](https://hacktoberfest.digitalocean.com/hacktoberfest-update)
